plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
    id "me.modmuss50.mod-publish-plugin" version "2.+"
}

version = "mc${archive_minecraft_version}-Fabric-${mod_version}"
group = project.maven_group
var realVersion = project.mod_version + '+fabric'

base {
    archivesName = project.archives_base_name
}

repositories {
    // REI
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.architectury.dev/" }

    maven { url "https://maven.terraformersmc.com/releases/" }

    // JEI
    maven { url "https://maven.blamejared.com/" }
    maven { url "https://modmaven.dev" }

    // LambDynamicLights
    maven {
        name = "Gegy"
        url = uri("https://maven.gegy.dev")
    }

    maven { url "https://api.modrinth.com/maven" }
}

loom {
    accessWidenerPath = file("src/main/resources/${project.mod_id}.classtweaker")
}

fabricApi {
    configureDataGeneration() {
        modId = project.mod_id
        client = true
        outputDirectory = file("src/generated/resources")
        createSourceSet = true
        strictValidation = true
    }
}

configurations.configureEach {
    resolutionStrategy {
        force("net.fabricmc:fabric-loader:$loader_version")
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    api("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    implementation "com.terraformersmc:modmenu:${project.modmenu_version}"

    implementation "me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}"
    implementation "dev.architectury:architectury-fabric:${project.architectury_version}"

//    compileOnlyApi "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}"
    implementation "mezz.jei:jei-26.1.2-fabric:${jei_version}"

    runtimeOnly "maven.modrinth:jade:${jade_version}+fabric"

    // https://modrinth.com/mod/kiwi/versions
    implementation(annotationProcessor("maven.modrinth:kiwi:26.0.18+fabric"))
//    implementation fileTree(dir: "libs", include: ["*.jar"])
//    annotationProcessor fileTree(dir: "libs", include: ["*.jar"])

    api("teamreborn:energy:${project.tr_energy_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    // https://modrinth.com/mod/shimmer!/versions
//    implementation "maven.modrinth:uBKACKpl:zh7cZkGa"

    compileOnly("dev.lambdaurora.lambdynamiclights:lambdynamiclights-api:${project.lambdynamiclights_version}")
    localRuntime("dev.lambdaurora.lambdynamiclights:lambdynamiclights-runtime:${project.lambdynamiclights_version}")
}

processResources {
    inputs.property "version", realVersion

    filesMatching("fabric.mod.json") {
        expand "version": realVersion
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 25
    it.options.compilerArgs.add("-Akiwi.useDataModule")
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude '**/*.bat'
    exclude '**/*.py'
    exclude("/assets/${project.mod_id}/lang/en_us.existing.json")
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

java {
//    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

publishMods {
    file = jar.archiveFile
    changelog = file('CHANGELOG.md').exists() ? file('CHANGELOG.md').text : ''
    type = ['release': STABLE, 'beta': BETA, 'alpha': ALPHA][release_type]
    modLoaders.add("fabric")
    modLoaders.add("quilt")
    displayName = "[Fabric ${supported_version}] ${mod_version}"
    version = realVersion

    curseforge {
        projectId = "558346"
        client = true
        server = true
        accessToken = providers.environmentVariable("CURSE_TOKEN")
        minecraftVersions.add(minecraft_version)
        requires("kiwi-fabric")
        optional("cloth-config")
    }
    modrinth {
        projectId = "lak1V0eP"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)
        requires("kiwi")
        optional("cloth-config")
    }
}