org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en
org.gradle.daemon=false
org.gradle.configuration-cache=false

# NeoForge Properties
# check these on https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.1.2
archive_minecraft_version=26.1
supported_version=26.1.X
loader_version=26.1.2.100

# Mod Properties
mod_version=26.0.2
release_type=release
mod_id=lightingwand
maven_group=snownee.lightingwand
archives_base_name=LightingWand

# Dependencies
cloth_config_version=26.1.154
rei_version=16.0.799
jei_version=29.33.0.87
jade_version=26.1.10
# https://modrinth.com/mod/lambdynamiclights/versions
lambdynamiclights_version=4.11.1+26.1.2