org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=26.1.2
archive_minecraft_version=26.1
supported_version=26.1.X
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=26.0.2
release_type=release
mod_id=lightingwand
maven_group=snownee.lightingwand
archives_base_name=LightingWand

# Dependencies
fabric_api_version=0.155.2+26.1.2
cloth_config_version=26.1.154
# https://modrinth.com/mod/modmenu/versions
modmenu_version=18.0.0
# https://modrinth.com/mod/rei/versions
rei_version=26.1.819
# https://modrinth.com/mod/architectury-api/versions
architectury_version=20.0.12
# https://modrinth.com/mod/jei/versions
jei_version=29.29.0.77
tr_energy_version=5.0.0
# https://modrinth.com/mod/jade/versions
jade_version=26.1.9
# https://modrinth.com/mod/lambdynamiclights/versions
lambdynamiclights_version=4.11.1+26.1.2