org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.21.1
supported_version=1.21.1
archive_minecraft_version=1.21.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=9.0.2
release_type=beta
mod_id=lightingwand
maven_group=snownee.lightingwand
archives_base_name=LightingWand

# Dependencies
fabric_api_version=0.116.8+1.21.1
cloth_config_version=15.0.127
modmenu_version=11.0.0-beta.2
rei_version=16.0.729
jei_version=19.27.0.340
tr_energy_version=4.1.0
