modLoader = "javafml"
loaderVersion = "[44,)"
license = "MIT"

[[mods]]
modId = "lightingwand"
version = "${file.jarVersion}"
displayName = "Lighting Wand"
authors = "Snownee"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/lighting-wand"
description = "Lighting up!"

[[dependencies.lightingwand]]
modId = "kiwi"
mandatory = true
versionRange = "[11.6.2, 12)"
ordering = "NONE"
side = "BOTH"

[modproperties.lightingwand]
catalogueItemIcon = "lightingwand:wand" #Support for Catalogue mod
