modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "lightingwand"
version = "${file.jarVersion}"
displayName = "Lighting Wand"
authors = "Snownee"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/lighting-wand"
description = "Wand that can place invisible light source!"
credits = "SettingDust"

[[dependencies.lightingwand]]
modId = "kiwi"
versionRange = "[15,)"

[[mixins]]
config = "lightingwand.mixins.json"

[modproperties.lightingwand]
catalogueItemIcon = "lightingwand:wand" #Support for Catalogue mod

[modproperties.lightingwand."yumi:entrypoints"]
"lambdynlights:initializer" = "snownee.lightingwand.compat.lambdynlights.LWDynamicLightsInitializer"